#!/usr/bin/python3
import smtplib
import sys
import enum
import quopri

from email.message import EmailMessage

from db import EmailManager
from mailcomposer import MailComposer
from utils import get_email, get_dns_record

class State(enum.Enum):
    start = 0
    value = 1

opts = ['--to', '-t', '--from', '-f', '--name', '-n', '--message', '-m', '--subject', '-s', '--domain', '-d', '-w', '--folder', '-l', '--no-save', '-h', '--html', '--to-name', '--sign', '--raw-sign']

args = sys.argv

state = State.start
opt = None

data = {
    'to': [],
    'from': '',
    'domain': '',
    'sign': '',
    'raw_sign': None,
    'message': '',
    'html': None,
    'subject': '',
    'watermark': False,
    'folder': 'sent',
    'to_name': None,
    'no_save': False,
}

for arg in args:
    if state == State.start:
        if arg in opts:
            if arg == '-w':
                data['watermark'] = True
            elif arg == '--no-save':
                data['no_save'] = True
            else:
                state = State.value
                opt = arg

    else:
        if opt == '--to' or opt == '-t':
            for em in get_email(arg):
                data['to'].append(em)
        elif opt == '--from' or opt == '-f':
            if em := get_email(arg):
                data['from'] = em[0]
            else:
                print("Invalid from address")
                exit(1)
        elif opt == '--message' or opt == '-m':
            data['message'] = arg
        elif opt == '--subject' or opt == '-s':
            data['subject'] = arg
        elif opt == '--domain' or opt == '-d':
            data['domain'] = arg
        elif opt == '--name' or opt == '-n':
            data['name'] = arg
        elif opt == '--folder' or opt == '-l':
            data['folder'] = arg
        elif opt == '--html' or opt == '-h':
            data['html'] = arg
        elif opt == '--to-name':
            data['to_name'] = arg
        elif opt == '--sign':
            data['sign'] = arg
        elif opt == '--raw-sign':
            data['raw_sign'] = arg

        state = State.start

if not data['from'].strip():
    print("Specify from address using -f")
    exit(1)

user, domain = data['from'].split('@')
domain = data['domain'] or domain
to_real = ', '.join(data['to'])

if not data['to']:
    print("Specify at least 1 to address using -t")
    exit(2)

db = None

if not data['no_save']:
    db = EmailManager(f'{user}@{domain}')

composer = MailComposer(data.get('name', user), user, domain, ((data['to_name'] if data['to_name'] else '') + ' ' + to_real).strip(), subject = data['subject'])

if data['message']:
    composer.set_content(data['message'])

if data['raw_sign']:
    composer.message.add_header("DKIM-Signature", data['raw_sign'])
elif data['sign']:
    composer.sign(data['sign'], 'dragon', ('sayu@' + data['sign']) if data['sign'] != domain else data['from'])
else:
    composer.sign(domain, 'dragon', data['from'])

if data['html']:
    html = EmailMessage()
    html.add_header("Content-Type", "text/html", charset="UTF-8")
    html.add_header("Content-Transfer-Encoding", "quoted-printable")
    html.set_payload(quopri.encodestring(data['html'].encode()).decode())
    composer.message.attach(html)
else:
    composer.set_html(data['message'], watermark = data['watermark'])

segmented_mails = {}

for em in data['to']:
    domain = em.split('@')[1]
    segmented_mails.setdefault(domain.lower(), [])
    segmented_mails[domain.lower()].append(em)

for domain, emails in segmented_mails.items():
    records = get_dns_record(domain, 'MX')
    if not records:
        print(f"No mail servers found for {domain}. Skipping...")
        continue
    mx_server = min(records, key = lambda rec: rec.priority).value[:-1]
    try:
        client = smtplib.SMTP(mx_server, local_hostname='sayutel.com')
        client.sendmail(data['from'], emails, composer.get_bytes())
        client.close()
    except smtplib.SMTPRecipientsRefused:
        print('Recipient: ' + data['from'] + ' refused by mail server ' + mx_server + ' for ' + domain + '. Skipping...')

if db:
    db.add_mail(data['folder'], composer.message, data['from'], to_real)